spring.application.name=backend




# H2 Database configuration (File mode)
spring.datasource.url=jdbc:h2:file:./data/license_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Nom et emplacement du fichier
logging.file.path=./logs

# Formatage pour une lecture propre dans Angular
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# (Optionnel) Rotation des logs pour éviter un fichier de 10 Go
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.total-size-cap=100MB


#Configuration
signature.key=cXdlcnR5dWlvcGFzZGZnaGprbHp4Y2d2Ym5tbTk4NzY1NDMxMjM0NTY3ODk4NzY1NDMxMjM0NTY3ODk4NzY1NDMxMjM=
#encryption.key=abc123def456ghi789jkl012mno345pq
access.expired.time=999999999999
refresh.expired.time=2592000000000